---
sudo: required
dist: trusty
language: generic

env:
  - PLAYBOOK=test.yml

before_install:
  - sudo apt-get update -qq

install:
  # install ansible
  - sudo pip install ansible

  # configure ansible
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # check syntax
  - "ansible-playbook -i tests/inventory tests/$PLAYBOOK --syntax-check"

  # initial run
  - "ansible-playbook -i tests/inventory tests/$PLAYBOOK --connection=local --sudo"

  # check idempotence
  - "ansible-playbook -i tests/inventory tests/$PLAYBOOK --connection=local --sudo"

  # check that ntp is installed
  - >
    ntpd --version
    | grep -q 'ntpd\s[0-9]'
    && (echo 'ntp is installed' && exit 0)
    || (echo 'ntp is not installed' && exit 1)

  # check that ntp is running
  - >
    sudo service ntp status
    | grep -q 'is running'
    && (echo 'ntp is running' && exit 0)
    || (echo 'ntp is not running' && exit 1)
