---
- name: service | ntp | started
  service:
    name: ntpd
    state: started

- name: service | ntp | stopped
  service:
    name: ntpd
    state: stopped

- name: service | ntp | restarted
  service:
    name: ntpd
    state: restarted

- name: service | ntp | reloaded
  service:
    name: ntpd
    state: reloaded
